[package]
name = "InGameHeroSwitch"
namespace = "doombubbles"
description = "Lets you press the PageUp and PageDown keys (configurable) to cycle your hero while in a game."
websiteUrl = "https://github.com/doombubbles/InGameHeroSwitch"

[package.dependencies]
LavaGang-MelonLoader = "0.7.3"
doombubbles-Btd6ModHelper = "3.6.5"

[build]
icon = "./Icon.png"
readme = "./README.md"
outdir = "bin"

[[build.copy]]
source = "./bin/Release/InGameHeroSwitch.dll"
target = "InGameHeroSwitch.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = ["bloons-td-6"]
categories = ["mods"]
